project_id = "oonteavjxzkovrzktnie"

[functions.create-client-user]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.track-click]
verify_jwt = false

[functions.process-cadence]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false
