// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-companies.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "N\xE3o autenticado. Conecte-se novamente ao AdvOne." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function normalizePhone(input) {
  const digits = input.replace(/\D/g, "");
  if (digits.length <= 11 && !digits.startsWith("55")) return `55${digits}`;
  return digits;
}
function phoneVariants(input) {
  const p = normalizePhone(input);
  const set = /* @__PURE__ */ new Set([p, input.replace(/\D/g, "")]);
  if (p.length === 13) {
    set.add(p.slice(0, 4) + p.slice(5));
  } else if (p.length === 12) {
    set.add(p.slice(0, 4) + "9" + p.slice(4));
  }
  return [...set].filter(Boolean);
}
async function resolveCompanyId(ctx, companyId) {
  const supabase = supabaseForUser(ctx);
  if (companyId) {
    const { data: data2, error: error2 } = await supabase.from("companies").select("id").eq("id", companyId).maybeSingle();
    if (error2) return { error: error2.message };
    if (!data2) return { error: "Empresa n\xE3o encontrada ou sem acesso." };
    return { companyId: data2.id };
  }
  const { data, error } = await supabase.from("companies").select("id, name").order("created_at", { ascending: true }).limit(2);
  if (error) return { error: error.message };
  if (!data || data.length === 0) return { error: "Nenhuma empresa acess\xEDvel para este usu\xE1rio." };
  return { companyId: data[0].id };
}

// src/lib/mcp/tools/list-companies.ts
var list_companies_default = defineTool({
  name: "list_companies",
  title: "Listar escrit\xF3rios",
  description: "Lista os escrit\xF3rios (empresas) que o usu\xE1rio conectado pode acessar no AdvOne. Use o id retornado como company_id nas outras tools.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("companies").select("id, name, billing_model, service_mode, practice_specialty, message_quota_monthly, messages_used_current_period").order("name", { ascending: true });
    if (error) return errorResult(error.message);
    return jsonResult({ total: data?.length ?? 0, companies: data ?? [] }, { companies: data ?? [] });
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";
var LEAD_FIELDS = "id, name, phone, whatsapp, email, cpf, status, source, lead_score, case_area, case_subtype, case_urgency, case_summary_short, value, is_client, is_unread, bot_disabled, kanban_column_id, assigned_to, created_at, updated_at";
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads do CRM do escrit\xF3rio, com filtros por coluna do funil, status, score, busca por nome/telefone e pagina\xE7\xE3o. Respeita as permiss\xF5es do usu\xE1rio conectado.",
  inputSchema: {
    company_id: z.string().uuid().optional().describe("Escrit\xF3rio. Se omitido, usa o primeiro acess\xEDvel."),
    kanban_column_id: z.string().uuid().optional().describe("Filtra por coluna do funil."),
    status: z.string().optional().describe("Filtra por status do lead (ex: new, contacted, won, lost)."),
    lead_score: z.enum(["hot", "warm", "cold"]).optional().describe("Filtra pela temperatura do lead."),
    only_unread: z.boolean().optional().describe("Apenas leads com mensagem n\xE3o lida."),
    search: z.string().optional().describe("Busca parcial por nome ou telefone."),
    limit: z.number().int().min(1).max(200).default(50),
    offset: z.number().int().min(0).default(0)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select(LEAD_FIELDS, { count: "exact" }).eq("company_id", resolved.companyId).order("updated_at", { ascending: false }).range(input.offset, input.offset + input.limit - 1);
    if (input.kanban_column_id) query = query.eq("kanban_column_id", input.kanban_column_id);
    if (input.status) query = query.eq("status", input.status);
    if (input.lead_score) query = query.eq("lead_score", input.lead_score);
    if (input.only_unread) query = query.eq("is_unread", true);
    if (input.search) {
      const term = input.search.replace(/[%,]/g, "");
      query = query.or(`name.ilike.%${term}%,phone.ilike.%${term}%,whatsapp.ilike.%${term}%`);
    }
    const { data, error, count } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(
      { total: count ?? 0, limit: input.limit, offset: input.offset, leads: data ?? [] },
      { leads: data ?? [], total: count ?? 0 }
    );
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var get_lead_default = defineTool3({
  name: "get_lead",
  title: "Detalhes do lead",
  description: "Retorna o lead completo (dados do caso, dados processuais, coluna do funil, agendamentos e \xFAltimas mensagens) por id ou por telefone.",
  inputSchema: {
    company_id: z2.string().uuid().optional(),
    lead_id: z2.string().uuid().optional().describe("Id do lead."),
    phone: z2.string().optional().describe("Telefone do lead (aceita varia\xE7\xF5es com/sem nono d\xEDgito).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (!input.lead_id && !input.phone) return errorResult("Informe lead_id ou phone.");
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select("*").eq("company_id", resolved.companyId).limit(1);
    if (input.lead_id) {
      query = query.eq("id", input.lead_id);
    } else {
      const variants = phoneVariants(input.phone);
      const filter = variants.flatMap((v) => [`phone.eq.${v}`, `whatsapp.eq.${v}`]).join(",");
      query = query.or(filter);
    }
    const { data: leads, error } = await query;
    if (error) return errorResult(error.message);
    const lead = leads?.[0];
    if (!lead) return errorResult("Lead n\xE3o encontrado.");
    const [{ data: column }, { data: events }, { data: messages }] = await Promise.all([
      lead.kanban_column_id ? supabase.from("kanban_columns").select("id, name, position").eq("id", lead.kanban_column_id).maybeSingle() : Promise.resolve({ data: null }),
      supabase.from("lead_reminders").select("id, title, description, due_at, end_at, reminder_type, completed, meeting_held").eq("lead_id", lead.id).order("due_at", { ascending: false }).limit(10),
      supabase.from("whatsapp_messages").select("direction, message_text, sender_name, timestamp").eq("company_id", resolved.companyId).eq("phone", lead.phone ?? lead.whatsapp ?? "").order("timestamp", { ascending: false }).limit(10)
    ]);
    return jsonResult({
      lead,
      kanban_column: column ?? null,
      agendamentos: events ?? [],
      ultimas_mensagens: (messages ?? []).reverse()
    });
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var create_lead_default = defineTool4({
  name: "create_lead",
  title: "Criar lead",
  description: "Cria um lead no CRM do escrit\xF3rio. Se j\xE1 existir lead com o mesmo telefone, faz merge dos campos enviados preservando o hist\xF3rico e a conversa.",
  inputSchema: {
    company_id: z3.string().uuid().optional(),
    name: z3.string().trim().min(1).max(200).describe("Nome do lead."),
    phone: z3.string().trim().min(8).max(20).describe("Telefone com DDI+DDD+n\xFAmero."),
    email: z3.string().trim().email().max(255).optional(),
    cpf: z3.string().trim().max(20).optional(),
    source: z3.string().optional().describe("Canal de origem (ex: google_ads, meta_ads, organic, indicacao)."),
    notes: z3.string().max(4e3).optional().describe("Descri\xE7\xE3o/observa\xE7\xF5es do caso."),
    case_area: z3.string().max(100).optional().describe("\xC1rea do direito (ex: trabalhista, previdenciario)."),
    kanban_column_id: z3.string().uuid().optional().describe("Coluna do funil de destino.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    const phone = normalizePhone(input.phone);
    const variants = phoneVariants(input.phone);
    const { data: existing } = await supabase.from("leads").select("id").eq("company_id", resolved.companyId).or(variants.flatMap((v) => [`phone.eq.${v}`, `whatsapp.eq.${v}`]).join(",")).limit(1);
    const payload = {
      name: input.name,
      phone,
      whatsapp: phone,
      ...input.email ? { email: input.email } : {},
      ...input.cpf ? { cpf: input.cpf } : {},
      ...input.source ? { source: input.source } : {},
      ...input.notes ? { notes: input.notes } : {},
      ...input.case_area ? { case_area: input.case_area } : {},
      ...input.kanban_column_id ? { kanban_column_id: input.kanban_column_id } : {}
    };
    if (existing?.[0]) {
      const { data: data2, error: error2 } = await supabase.from("leads").update(payload).eq("id", existing[0].id).select("id, name, phone, status, kanban_column_id").maybeSingle();
      if (error2) return errorResult(error2.message);
      return jsonResult({ merged: true, lead: data2 }, { lead: data2, merged: true });
    }
    const { data, error } = await supabase.from("leads").insert({ ...payload, company_id: resolved.companyId }).select("id, name, phone, status, kanban_column_id").maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ merged: false, lead: data }, { lead: data, merged: false });
  }
});

// src/lib/mcp/tools/update-lead.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var update_lead_default = defineTool5({
  name: "update_lead",
  title: "Atualizar lead",
  description: "Atualiza dados de um lead existente: nome, e-mail, CPF, status, temperatura (score), \xE1rea do caso, valor estimado ou observa\xE7\xF5es.",
  inputSchema: {
    company_id: z4.string().uuid().optional(),
    lead_id: z4.string().uuid().describe("Id do lead a atualizar."),
    name: z4.string().trim().min(1).max(200).optional(),
    email: z4.string().trim().email().max(255).optional(),
    cpf: z4.string().trim().max(20).optional(),
    status: z4.string().optional().describe("Novo status do lead."),
    lead_score: z4.enum(["hot", "warm", "cold"]).optional(),
    case_area: z4.string().max(100).optional(),
    value: z4.number().nonnegative().optional().describe("Valor estimado da causa."),
    notes: z4.string().max(4e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const { company_id: _ignored, lead_id, ...fields } = input;
    const payload = Object.fromEntries(
      Object.entries(fields).filter(([, v]) => v !== void 0)
    );
    if (Object.keys(payload).length === 0) return errorResult("Nenhum campo para atualizar.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").update(payload).eq("id", lead_id).eq("company_id", resolved.companyId).select("id, name, phone, email, status, lead_score, case_area, value").maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Lead n\xE3o encontrado ou sem permiss\xE3o de edi\xE7\xE3o.");
    return jsonResult({ lead: data }, { lead: data });
  }
});

// src/lib/mcp/tools/list-funnel-columns.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_funnel_columns_default = defineTool6({
  name: "list_funnel_columns",
  title: "Listar funis e colunas",
  description: "Lista os quadros (funis) e colunas do Kanban comercial do escrit\xF3rio, com contagem de leads por coluna. Use os ids para mover leads.",
  inputSchema: {
    company_id: z5.string().uuid().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    const [{ data: boards }, { data: columns, error }] = await Promise.all([
      supabase.from("kanban_boards").select("id, name").eq("company_id", resolved.companyId),
      supabase.from("kanban_columns").select("id, name, position, board_id, is_won, is_lost, is_urgent, is_meeting_held").eq("company_id", resolved.companyId).order("position", { ascending: true })
    ]);
    if (error) return errorResult(error.message);
    const boardList = boards ?? [];
    const grouped = [
      ...boardList.map((b) => ({
        board_id: b.id,
        board_name: b.name,
        columns: (columns ?? []).filter((c) => c.board_id === b.id)
      })),
      {
        board_id: null,
        board_name: "Sem quadro",
        columns: (columns ?? []).filter((c) => !c.board_id)
      }
    ].filter((g) => g.columns.length > 0);
    return jsonResult({ funnels: grouped }, { funnels: grouped });
  }
});

// src/lib/mcp/tools/move-lead-column.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^4.4.3";
var move_lead_column_default = defineTool7({
  name: "move_lead_column",
  title: "Mover lead no funil",
  description: "Move um lead para outra coluna do funil Kanban. A coluna precisa pertencer ao mesmo escrit\xF3rio do lead.",
  inputSchema: {
    company_id: z6.string().uuid().optional(),
    lead_id: z6.string().uuid(),
    kanban_column_id: z6.string().uuid().describe("Coluna de destino (ver list_funnel_columns).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    const { data: column } = await supabase.from("kanban_columns").select("id, name, is_won, is_lost").eq("id", input.kanban_column_id).eq("company_id", resolved.companyId).maybeSingle();
    if (!column) return errorResult("Coluna n\xE3o encontrada neste escrit\xF3rio.");
    const { data, error } = await supabase.from("leads").update({ kanban_column_id: column.id }).eq("id", input.lead_id).eq("company_id", resolved.companyId).select("id, name, kanban_column_id").maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Lead n\xE3o encontrado ou sem permiss\xE3o.");
    return jsonResult({ lead: data, column }, { lead: data, column });
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^4.4.3";
var list_conversations_default = defineTool8({
  name: "list_conversations",
  title: "Listar conversas WhatsApp",
  description: "Lista as conversas de WhatsApp do escrit\xF3rio ordenadas pela atividade mais recente, com nome do lead, \xFAltima mensagem, se est\xE1 sem resposta e se o bot est\xE1 ativo.",
  inputSchema: {
    company_id: z7.string().uuid().optional(),
    only_unread: z7.boolean().optional().describe("Apenas conversas com mensagem n\xE3o lida."),
    limit: z7.number().int().min(1).max(100).default(30)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    const { data: messages, error } = await supabase.from("whatsapp_messages").select("phone, message_text, direction, sender_name, timestamp").eq("company_id", resolved.companyId).order("timestamp", { ascending: false }).limit(1e3);
    if (error) return errorResult(error.message);
    const byPhone = /* @__PURE__ */ new Map();
    for (const m of messages ?? []) {
      const current = byPhone.get(m.phone);
      if (!current) {
        byPhone.set(m.phone, {
          phone: m.phone,
          ultima_mensagem: m.message_text,
          direcao: m.direction,
          ultima_mensagem_em: m.timestamp,
          total_mensagens: 1
        });
      } else {
        current.total_mensagens += 1;
      }
    }
    const phones = [...byPhone.keys()];
    const { data: leads } = phones.length ? await supabase.from("leads").select("id, name, phone, whatsapp, is_unread, bot_disabled, lead_score, status").eq("company_id", resolved.companyId).or(phones.map((p) => `phone.eq.${p},whatsapp.eq.${p}`).join(",")) : { data: [] };
    const leadByPhone = /* @__PURE__ */ new Map();
    for (const l of leads ?? []) {
      if (l.phone) leadByPhone.set(l.phone, l);
      if (l.whatsapp) leadByPhone.set(l.whatsapp, l);
    }
    let conversations = [...byPhone.values()].map((c) => {
      const lead = leadByPhone.get(c.phone);
      return {
        ...c,
        lead_id: lead?.id ?? null,
        nome: lead?.name ?? null,
        nao_lida: lead?.is_unread ?? false,
        bot_ativo: lead ? !lead.bot_disabled : null,
        lead_score: lead?.lead_score ?? null,
        status: lead?.status ?? null,
        aguardando_resposta_do_escritorio: c.direcao === "incoming"
      };
    }).sort((a, b) => b.ultima_mensagem_em.localeCompare(a.ultima_mensagem_em));
    if (input.only_unread) conversations = conversations.filter((c) => c.nao_lida);
    return jsonResult(
      { total: conversations.length, conversations: conversations.slice(0, input.limit) },
      { conversations: conversations.slice(0, input.limit) }
    );
  }
});

// src/lib/mcp/tools/get-conversation.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z8 } from "npm:zod@^4.4.3";
var get_conversation_default = defineTool9({
  name: "get_conversation",
  title: "Ler conversa WhatsApp",
  description: "Retorna o hist\xF3rico de mensagens trocadas com um contato em ordem cronol\xF3gica, identificado por telefone ou lead_id.",
  inputSchema: {
    company_id: z8.string().uuid().optional(),
    phone: z8.string().optional().describe("Telefone do contato."),
    lead_id: z8.string().uuid().optional().describe("Id do lead."),
    limit: z8.number().int().min(1).max(500).default(100)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (!input.phone && !input.lead_id) return errorResult("Informe phone ou lead_id.");
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    let phones = [];
    let leadName = null;
    if (input.lead_id) {
      const { data: lead } = await supabase.from("leads").select("name, phone, whatsapp").eq("id", input.lead_id).eq("company_id", resolved.companyId).maybeSingle();
      if (!lead) return errorResult("Lead n\xE3o encontrado.");
      leadName = lead.name;
      phones = [lead.phone, lead.whatsapp].filter((p) => Boolean(p));
    } else {
      phones = phoneVariants(input.phone);
    }
    if (phones.length === 0) return errorResult("Contato sem telefone cadastrado.");
    const { data, error } = await supabase.from("whatsapp_messages").select("direction, message_text, sender_name, timestamp, phone").eq("company_id", resolved.companyId).in("phone", phones).order("timestamp", { ascending: false }).limit(input.limit);
    if (error) return errorResult(error.message);
    const mensagens = (data ?? []).reverse().map((m) => ({
      de: m.direction === "incoming" ? "lead" : m.sender_name ?? "escritorio",
      texto: m.message_text,
      em: m.timestamp
    }));
    return jsonResult({ contato: leadName, phones, total: mensagens.length, mensagens }, { mensagens });
  }
});

// src/lib/mcp/tools/send-whatsapp-message.ts
import { defineTool as defineTool10, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z9 } from "npm:zod@^4.4.3";
var send_whatsapp_message_default = defineTool10({
  name: "send_whatsapp_message",
  title: "Enviar mensagem WhatsApp",
  description: "Envia uma mensagem de WhatsApp para um contato pelo n\xFAmero conectado do escrit\xF3rio. Aten\xE7\xE3o: envia de verdade ao cliente e desativa o bot naquela conversa (assume atendimento humano). Confirme com o usu\xE1rio antes de disparar.",
  inputSchema: {
    company_id: z9.string().uuid().optional(),
    phone: z9.string().trim().min(8).max(20).describe("Destinat\xE1rio com DDI+DDD+n\xFAmero."),
    message: z9.string().trim().min(1).max(4e3).describe("Texto da mensagem.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const token = ctx.getToken();
    if (!token) return notAuthenticated();
    const res = await fetch(`${supabaseProjectUrl()}/functions/v1/send-whatsapp`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
      body: JSON.stringify({
        company_id: resolved.companyId,
        phone: normalizePhone(input.phone),
        message: input.message
      })
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) {
      throw new ToolError(
        `Falha ao enviar (${res.status}): ${body.error ?? "erro desconhecido"}`
      );
    }
    return jsonResult({ enviado: true, message_id: body.message_id ?? null });
  }
});

// src/lib/mcp/tools/list-monitored-processes.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z10 } from "npm:zod@^4.4.3";
var list_monitored_processes_default = defineTool11({
  name: "list_monitored_processes",
  title: "Listar processos monitorados",
  description: "Lista os processos judiciais monitorados do escrit\xF3rio (n\xFAmero CNJ, cliente, tribunal, \xFAltima movimenta\xE7\xE3o e status previsto).",
  inputSchema: {
    company_id: z10.string().uuid().optional(),
    search: z10.string().optional().describe("Busca por nome do cliente, CPF ou n\xFAmero CNJ."),
    only_active: z10.boolean().default(true),
    limit: z10.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("monitored_processes").select(
      "id, numero_cnj, client_name, client_cpf, tribunal_sigla, area, classe, assunto, polo_ativo, polo_passivo, status_predito, quantidade_movimentacoes, data_ultima_movimentacao, last_checked_at, is_active",
      { count: "exact" }
    ).eq("company_id", resolved.companyId).order("data_ultima_movimentacao", { ascending: false, nullsFirst: false }).limit(input.limit);
    if (input.only_active) query = query.eq("is_active", true);
    if (input.search) {
      const term = input.search.replace(/[%,]/g, "");
      query = query.or(
        `client_name.ilike.%${term}%,client_cpf.ilike.%${term}%,numero_cnj.ilike.%${term}%`
      );
    }
    const { data, error, count } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ total: count ?? 0, processos: data ?? [] }, { processos: data ?? [] });
  }
});

// src/lib/mcp/tools/get-process-status.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z11 } from "npm:zod@^4.4.3";
var get_process_status_default = defineTool12({
  name: "get_process_status",
  title: "Situa\xE7\xE3o do processo",
  description: "Retorna a situa\xE7\xE3o atual de um processo monitorado pelo n\xFAmero CNJ, com as \xFAltimas movimenta\xE7\xF5es em ordem cronol\xF3gica, para explicar em linguagem simples o que aconteceu.",
  inputSchema: {
    company_id: z11.string().uuid().optional(),
    numero_cnj: z11.string().trim().min(15).max(30).describe("N\xFAmero CNJ do processo (com ou sem m\xE1scara)."),
    movements_limit: z11.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const resolved = await resolveCompanyId(ctx, input.company_id);
    if ("error" in resolved) return errorResult(resolved.error);
    const digits = input.numero_cnj.replace(/\D/g, "");
    const supabase = supabaseForUser(ctx);
    const { data: processes, error } = await supabase.from("monitored_processes").select("*").eq("company_id", resolved.companyId).limit(500);
    if (error) return errorResult(error.message);
    const processo = (processes ?? []).find((p) => p.numero_cnj.replace(/\D/g, "") === digits);
    if (!processo) {
      return errorResult(
        "Processo n\xE3o encontrado no monitoramento deste escrit\xF3rio. Cadastre o processo no AdvOne para acompanh\xE1-lo."
      );
    }
    const { data: movimentacoes } = await supabase.from("process_movements").select("movement_date, movement_type, content, source_name, source_grau, source_provider").eq("monitored_process_id", processo.id).order("movement_date", { ascending: false }).limit(input.movements_limit);
    return jsonResult({
      processo: {
        numero_cnj: processo.numero_cnj,
        cliente: processo.client_name,
        tribunal: processo.tribunal_sigla,
        area: processo.area,
        classe: processo.classe,
        assunto: processo.assunto,
        polo_ativo: processo.polo_ativo,
        polo_passivo: processo.polo_passivo,
        status_predito: processo.status_predito,
        total_movimentacoes: processo.quantidade_movimentacoes,
        ultima_movimentacao_em: processo.data_ultima_movimentacao,
        ultima_verificacao: processo.last_checked_at
      },
      movimentacoes: (movimentacoes ?? []).reverse()
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "oonteavjxzkovrzktnie";
var mcp_default = defineMcp({
  name: "advone",
  title: "AdvONe",
  version: "1.0.0",
  instructions: [
    "Ferramentas do AdvOne \u2014 CRM jur\xEDdico com SDR de IA no WhatsApp, funil Kanban e monitoramento processual.",
    "O usu\xE1rio conecta com a pr\xF3pria conta AdvOne: todas as tools respeitam as permiss\xF5es e o escrit\xF3rio dele.",
    "Comece por `list_companies` quando houver mais de um escrit\xF3rio; nas demais tools o company_id \xE9 opcional.",
    "Use `list_leads`/`get_lead` para consultar o CRM, `list_funnel_columns` + `move_lead_column` para o funil,",
    "`list_conversations`/`get_conversation` para o hist\xF3rico de WhatsApp e `list_monitored_processes`/`get_process_status`",
    "para acompanhar processos judiciais e explicar movimenta\xE7\xF5es em linguagem simples.",
    "`send_whatsapp_message` envia mensagem real ao cliente e assume o atendimento humano (desativa o bot na conversa):",
    "sempre confirme o n\xFAmero e o texto com o usu\xE1rio antes de chamar."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_companies_default,
    list_leads_default,
    get_lead_default,
    create_lead_default,
    update_lead_default,
    list_funnel_columns_default,
    move_lead_column_default,
    list_conversations_default,
    get_conversation_default,
    send_whatsapp_message_default,
    list_monitored_processes_default,
    get_process_status_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
